name: 4-action-azure-aks

on:
  push:
    branches:
    - dev
    - master
    paths:
    - azure/arm/*
    - .github/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: bash DEPLOY.sh
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        cd $GITHUB_WORKSPACE/
        export SP_NAME=$(echo $AZURE_CREDENTIALS | jq -r .name)
        export SP_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .appId)
        export SP_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .password)
        echo "SP_NAME: ${SP_NAME}"
        bash azure/arm/DEPLOY.sh
        